name: Keep Render Awake

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your Render bot
        run: curl -s https://bachatareminder.onrender.com
